### ISSUE TITLE
trollflow fails when satpy warns about "Delaying generation ... because of incompatible areas"

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/trollflow-sat#7]
When a product needs resampling and satpy.scene reports "Delaying generation of ... because of incompatible areas" the trollflow-sat fails.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run self.__target(*self.__args, **self.__kwargs)
  File "/software/pytroll/lib/python2.7/site-packages/trollflow_sat-0.8.0-py2.7.egg/trollflow_sat/satpy_writer.py", line 184, in run lcl.save_dataset(dataset_ids[i],
IndexError: list index out of range

Here https://github.com/pytroll/trollflow-sat/blob/master/trollflow_sat/satpy_resampler.py#L88 the dataset_ids as assigned to an empty list instead of the products name, like overview. This happens with GOES-16 eumetcast data where some channel have a slightly different projection coefficients and for overview product all channels needs to be resampled.

For AVHRR data this works fine as all channels have the same projection coefficients.

I don't have a suggestion for solution, but if I hardcode the https://github.com/pytroll/trollflow-sat/blob/master/trollflow_sat/satpy_resampler.py#L101 to:
lcl.info["dataset_ids"] = ['overview'] it works, so the dataset_ids list needs to contain the product name instead of an empty list.

**Comment by pnuu** [comment]
I just ran in to this same case with VIIRS data. I'll start looking in to it how to fix this.

**Comment by pnuu** [comment]
Fixed by #9 .
